spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:com.ww.jwt_demo.mapper/*.xml

logging:
  level:
    com.ww.jwt_demo.mapper: debug
